#!/bin/bash -e

function message {
    TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
    echo -e "[${TIMESTAMP}] [vbox-cleanup] ${1}"
}

message "VBox Cleanup script"
message "Started"

message "Cleaning packages"
apt-get -y autoremove
apt-get -y clean

message "Complete"
