Vagrant.configure("2") do |config|
  config.vm.box = "file://build/mysql-8-centos-7-x86_64.box"
  #config.vm.synced_folder ".", "/vagrant"
  config.ssh.username = "packer"
  config.ssh.password = "packer"
  config.ssh.insert_key = false
  config.vm.define "virtualbox" do |virtualbox|
    virtualbox.vm.hostname = "test1"
    virtualbox.vm.network :private_network, ip: "10.0.0.2"
    config.vm.provider :virtualbox do |v|
      v.gui = false
      v.cpus = 1
      v.memory = 1024
    end
  end
end
