#!/bin/bash -eux

MYSQL_PASSWORD=Password1234!
MYSQL_SERVER_VERSION=8.0.13.el7
MYSQL_SHELL_VERSION=8.0.13.el7
MYSQL_URL=https://dev.mysql.com/downloads/file/?id=477146
MYSQL_CHECKSUM=739dc44566d739c5d7b893de96ee6848
MYSQL_REPO=mysql80-community-release-el7-1.noarch.rpm

function message {
    TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
    echo -e "[${TIMESTAMP}] [mysql-8] ${1}"
}

message "MySQL 8 install script"
message "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
message "MYSQL_SERVER_VERSION=${MYSQL_SERVER_VERSION}"
message "MYSQL_SHELL_VERSION=${MYSQL_SHELL_VERSION}"
message "MYSQL_URL=${MYSQL_URL}"
message "MYSQL_CHECKSUM=${MYSQL_CHECKSUM}"
message "MYSQL_REPO=${MYSQL_REPO}"
message "Started"

message "Checking for existing MySQL repo"
if [ ! -f /tmp/${MYSQL_REPO} ]
then
    message "Downloading MySQL repo"
    curl --silent --location --output /tmp/${MYSQL_REPO} ${MYSQL_URL}
else
    message "MySQL repo exists, skipping download"
fi

message "Checking MySQL repo"
echo "${MYSQL_REPO}  /tmp/${MYSQL_REPO}" > /tmp/mysql-checksum
md5sum --quiet --check /tmp/mysql-checksum
rm /tmp/mysql-checksum

message "Installing MySQL repo"
rpm -Uvh /tmp/${MYSQL_REPO}
rm /tmp/${MYSQL_REPO}

message "Installing MySQL server"
yum install -y mysql-community-server-${MYSQL_SERVER_VERSION}

message "Installing MySQL shell"
yum install -y mysql-shell-${MYSQL_SHELL_VERSION}

message "Enabling and starting MySQL service"
systemctl --quiet enable mysqld.service
systemctl --quiet start mysqld.service

message "Wait for 60s for MySQL to start"
sleep 60

message "Change temporary root password"
MYSQL_TMP_PASSWORD=$(grep 'temporary password' /var/log/mysqld.log)
mysql \
    --user=root \
    --password=${MYSQL_TMP_PASSWORD} \
    --execute="ALTER USER 'root'@'localhost' IDENTIFIED BY '${MYSQL_PASSWORD}';" \
    > /dev/null

message "Stop MySQL service"
systemctl --quiet stop mysqld.service

message "Complete"
