#!/bin/bash -e

MYSQL_URL="https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm"
MYSQL_CHECKSUM=893b55d5d885df5c4d4cf7c4f2f6c153
MYSQL_REPO=mysql80-community-release-el7-3.noarch.rpm

function message {
    TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
    echo -e "[${TIMESTAMP}] [mysql-8] ${1}"
}

message "MySQL 8 install script"

if [ -z "${MYSQL_PASSWORD}" ]; then
  message "ERROR: Require 'MYSQL_PASSWORD' to be set"
  exit 1
fi

message "MYSQL_SERVER_VERSION=${MYSQL_SERVER_VERSION}"
message "MYSQL_SHELL_VERSION=${MYSQL_SHELL_VERSION}"
message "MYSQL_URL=${MYSQL_URL}"
message "MYSQL_CHECKSUM=${MYSQL_CHECKSUM}"
message "MYSQL_REPO=${MYSQL_REPO}"
message "Started"

message "Checking for existing MySQL repo"
if [ ! -f "/tmp/${MYSQL_REPO}" ]
then
    message "Downloading MySQL repo"
    curl --silent --location --output "/tmp/${MYSQL_REPO}" "${MYSQL_URL}"

    message "Checking MySQL repo"
    echo "${MYSQL_CHECKSUM}  /tmp/${MYSQL_REPO}" > /tmp/mysql-checksum
    md5sum --quiet --check /tmp/mysql-checksum
    rm /tmp/mysql-checksum

    message "Installing MySQL repo"
    rpm -Uvh "/tmp/${MYSQL_REPO}"
    rm "/tmp/${MYSQL_REPO}"
else
    message "MySQL repo exists, skipping download"
fi

message "Installing MySQL server"
yum install -y "mysql-community-server"

message "Installing MySQL shell"
yum install -y "mysql-shell"

message "Enabling and starting MySQL service"
systemctl --quiet enable mysqld.service
systemctl --quiet start mysqld.service

message "Wait for 60s for MySQL to start"
sleep 60

message "Change temporary root password"
MYSQL_TMP_PASSWORD="$(grep 'temporary password' /var/log/mysqld.log | awk '{ print $13 }')"
mysql \
    --connect-expired-password \
    --user=root \
    --password="${MYSQL_TMP_PASSWORD}" \
    --execute="ALTER USER 'root'@'localhost' IDENTIFIED BY '${MYSQL_PASSWORD}';"

message "Stop MySQL service"
systemctl --quiet stop mysqld.service

message "Complete"
