#!/bin/bash -e

function message {
    TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
    echo -e "[${TIMESTAMP}] [vbox-setup] ${1}"
}

message "VBox Setup script"
message "Started"

message "Installing packages"
yum -y install \
    bzip2 \
    curl \
    dkms \
    gcc \
    kernel-headers \
    kernel-devel \
    make \
    net-tools \
    nfs-utils \
    openssh-clients \
    openssl-devel \
    perl \
    readline-devel \
    unzip \
    vim-minimal

message "Complete"
