#!/bin/bash -e

CONSUL_USER=consul
CONSUL_CONFIG_DIR=/etc/consul.d
CONSUL_CONFIG_FILE=mysql.json

function message {
    TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
    echo -e "[${TIMESTAMP}] [consul-mysql] ${1}"
}

message "Consul MySQL service install script"
message "CONSUL_USER=${CONSUL_USER}"
message "CONSUL_CONFIG_DIR=${CONSUL_CONFIG_DIR}"
message "CONSUL_CONFIG_FILE=${CONSUL_CONFIG_FILE}"
message "Started"

message "Installing Consul MySQL Service config file"
cat > "${CONSUL_CONFIG_DIR}/${CONSUL_CONFIG_FILE}" <<EOF
{
  "service": {
    "name": "mysql",
    "tags": ["mysql"],
    "port": 3306,
    "checks": [
      {
        "id": "mysql",
        "name": "TCP on port 3306",
        "tcp": "localhost:3306",
        "interval": "10s",
        "timeout": "1s"
      }
    ]
  }
}
EOF
chown "${CONSUL_USER}":"${CONSUL_USER}" "${CONSUL_CONFIG_DIR}/${CONSUL_CONFIG_FILE}"

message "Complete"
