#!/bin/bash -eux

function message {
    TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
    echo -e "[${TIMESTAMP}] [vbox-additions] ${1}"
}

message "VBox Additions script"
message "Started"

VBOX_VERSION=$(cat /home/packer/.vbox_version)
VBOX_GUEST_ADDITIONS_ISO=/home/packer/VBoxGuestAdditions_${VBOX_VERSION}.iso

message "Mounting guest additions ISO"
mount -o loop ${VBOX_GUEST_ADDITIONS_ISO} /mnt

message "Running guest additions script"
sh /mnt/VBoxLinuxAdditions.run

message "Unmounting guest additions ISO"
umount /mnt > /dev/null

message "Deleting guest additions ISO"
rm -rf ${VBOX_GUEST_ADDITIONS_ISO}

message "Complete"
