#!/bin/bash -eux

function message {
    TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
    echo -e "[${TIMESTAMP}] [vbox-cleanup] ${1}"
}

message "VBox Cleanup script"
message "Started"

message "Cleaning packages"
apt autoremove
apt update

# message "Zero out free space"
# dd if=/dev/zero of=/EMPTY bs=1M
# rm -f /EMPTY
# sync

message "Complete"
