#!/bin/bash -eux

function message {
    TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
    echo -e "[${TIMESTAMP}] [vbox-additions] ${1}"
}

message "VBox Additions script"
message "Started"

message "VBOX_VERSION=${VBOX_VERSION}"

VBOX_PACKER_VERSION=$(cat /home/packer/.vbox_version)
VBOX_VERSION="${VBOX_VERSION:-$VBOX_PACKER_VERSION}"
VBOX_GUEST_ADDITIONS_URL="http://download.virtualbox.org/virtualbox/${VBOX_VERSION}/VBoxGuestAdditions_${VBOX_VERSION}.iso"

message "VBOX_PACKER_VERSION=${VBOX_PACKER_VERSION}"
message "Using VBOX_VERSION=${VBOX_VERSION}"
message "VBOX_GUEST_ADDITIONS_URL=${VBOX_GUEST_ADDITIONS_URL}"

curl --output VBoxGuestAdditions.iso "${VBOX_GUEST_ADDITIONS_URL}"

message "Mounting guest additions ISO"
mount -o loop VBoxGuestAdditions.iso /mnt

message "Running guest additions script"
sh /mnt/VBoxLinuxAdditions.run --nox11 || true

message "Unmounting guest additions ISO"
umount /mnt > /dev/null

message "Deleting guest additions ISO"
rm -rf VBoxGuestAdditions.iso

message "Complete"
